# File Tree: my-app

**Generated:** 3/16/2026, 10:44:38 PM
**Root Path:** `d:\BetterAuth\my-app`

```
├── 📁 public
│   ├── 🖼️ file.svg
│   ├── 🖼️ globe.svg
│   ├── 🖼️ next.svg
│   ├── 🖼️ vercel.svg
│   └── 🖼️ window.svg
├── 📁 src
│   ├── 📁 app
│   │   ├── 📁 (auth)
│   │   │   ├── 📁 forgot-password
│   │   │   │   └── 📄 page.tsx
│   │   │   ├── 📁 reset-password
│   │   │   │   └── 📄 page.tsx
│   │   │   ├── 📁 sign-in
│   │   │   │   └── 📄 page.tsx
│   │   │   └── 📁 sign-up
│   │   │       └── 📄 page.tsx
│   │   ├── 📁 api
│   │   │   └── 📁 auth
│   │   │       └── 📁 [...all]
│   │   │           └── 📄 route.ts
│   │   ├── 📁 dashboard
│   │   │   └── 📄 page.tsx
│   │   ├── 📁 verify-email
│   │   │   └── 📄 page.tsx
│   │   ├── 📄 favicon.ico
│   │   ├── 🎨 globals.css
│   │   ├── 📄 layout.tsx
│   │   └── 📄 page.tsx
│   ├── 📁 components
│   │   ├── 📁 ui
│   │   │   ├── 📄 button.tsx
│   │   │   ├── 📄 card.tsx
│   │   │   ├── 📄 input.tsx
│   │   │   └── 📄 label.tsx
│   │   └── 📄 sign-out-button.tsx
│   ├── 📁 generated
│   ├── 📁 lib
│   │   ├── 📄 auth-client.ts
│   │   ├── 📄 auth.ts
│   │   ├── 📄 email.ts
│   │   └── 📄 utils.ts
│   └── 📄 middleware.ts
├── ⚙️ .gitignore
├── 📝 README.md
├── ⚙️ components.json
├── 📄 eslint.config.mjs
├── 📄 next.config.ts
├── ⚙️ package-lock.json
├── ⚙️ package.json
├── 📄 postcss.config.mjs
└── ⚙️ tsconfig.json
```

---

_Generated by FileTree Pro Extension_
